freelancer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'freelancer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/', include('main.urls',namespace='main')),
    url(r'^', include('home.urls',namespace='home')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)
urlpatterns += patterns('',
   (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
       'document_root': settings.MEDIA_ROOT}))

home/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'freelancer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #urls of worker section
    url(r'^$', 'home.views.mainpage',name='mainpage'),
    url(r'^profile$', 'home.views.profile',name='profile'),
    url(r'^create_info$', 'home.views.create_info',name='create_info'),
    #url(r'^modify_info$', 'home.views.modify_info',name='modify_info'),
    #url(r'^change_password$', 'home.views.change_password',name='change_password'),
    #url(r'^modify_skills$', 'home.views.modify_skills',name='modify_skills'),
    #url(r'^list_jobs/(?P<category_id>.+)/$', 'home.views.list_jobs',name='list_jobs'),
    #url(r'^list_jobs/$','home.views.list_jobs',name='list_jobs'),
    #url(r'^job_info/(?P<job_id>.+)$', 'home.views.job_info',name='job_info'),
    #url(r'^delete_skill/(?P<skill_id>.+)$', 'home.views.delete_skill',name='delete_skill'),
    #urls of hirer section
    #url(r'^hire$', 'home.views.mainpage_hire',name='mainpage_hire'),
    url(r'^look_profile/(?P<worker_id>.+)$', 'home.views.look_profile',name='look_profile'),
    url(r'^list_workers/(?P<category_id>.+)/$', 'home.views.list_workers',name='list_workers'),
    url(r'^list_workers/$','home.views.list_workers',name='list_workers'),
    url(r'^add_task/$','home.views.add_task',name='add_task'),

    #url(r'^my_projects$', 'home.views.my_projects',name='my_projects'),
    #url(r'^delete_job/(?P<job_id>.+)$', 'home.views.delete_job',name='delete_job'),
)

main/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'freelancer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'main.views.mainpage',name='mainpage'),
    url(r'^signin$', 'main.views.signin',name='signin'),
    url(r'^signup$', 'main.views.signup',name='signup'),
    url(r'^signout$', 'main.views.signout',name='signout'),
)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Category(models.Model):
	"""Category class which owns skill"""

	title = models.CharField('категория',max_length=100)
	icon = models.ImageField('иконка', null=True, blank=True)

	def __unicode__(self):
		return self.title
	class Meta:
		verbose_name = "категория"
		verbose_name_plural = "категории"

class Skill(models.Model):
	"""this is class of skills which are is groupped by categories"""
	
	category = models.ForeignKey(Category, verbose_name='категория')
	title = models.CharField('навык', max_length=200)

	def __unicode__(self):
		return self.title +" ==> "+ self.category.title
	
	class Meta:
		verbose_name = "навык"
		verbose_name_plural = "навыки"

class Information(models.Model):
	"""This is class which stores all information about particular user"""
	
	def __unicode__(self):
		return self.user.first_name

	FEMALE = 'F'
	MALE = 'M'

	GENDER_CHOICE = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
	user = models.ForeignKey(User, verbose_name='пользователь')
	image = models.ImageField('фото', upload_to = 'media', null=True, blank=True)
	gender = models.CharField('пол', max_length=2,
                                      choices=GENDER_CHOICE,
                                      default=MALE)
	born_date = models.DateField('дата рождения', default=datetime.now, blank=True)
	phone_number = models.IntegerField('номер телефона')
	date = models.DateField('дата регистрации', default = datetime.now)
	stuff = models.BooleanField('исполнитель', default=False)
	category = models.ForeignKey(Category, verbose_name='категория')
	note = models.CharField('информация о пользователе', max_length=3000, null=True, blank=True)
	note_for_us = models.CharField('информация о для нас', max_length=3000, null=True, blank=True)
	note_of_prices = models.CharField('информация о делах и ценах', max_length=3000, null=True, blank=True)
	just_in_case = models.CharField('на всякий случай', max_length=3000, null=True, blank=True)
	id = models.AutoField(primary_key=True)
	


	class Meta:
		verbose_name = "анкета"
		verbose_name_plural = "анкеты"

class SkillofUser(models.Model):
	"""docstring for SkillofUser"""
	experience = models.IntegerField('стаж')

	skill = models.ForeignKey(Skill, verbose_name='навык')

	level = models.CharField('уровень навыка', max_length=11)
	user = models.ForeignKey(Information, verbose_name='пользователь')

	def __unicode__(self):
		return self.skill.title + ' ==> ' + self.user.user.username 
	
	class Meta:
		verbose_name = "навык пользователя"
		verbose_name_plural = "навыки пользователей"

class Job(models.Model):
	title = models.CharField('тема', max_length = 200)
	description = models.TextField('описание', null=True, blank=True)
	price = models.IntegerField('цена', null=True, blank=True)
	category = models.ForeignKey(Category, verbose_name='категория')
	date = models.DateTimeField('дата добавления', default=datetime.now)
	user = models.ForeignKey(User,default=None, verbose_name='пользователь')
	address = models.TextField('адрес', null=True, blank=True)

	def __unicode__(self):
		return self.title
	
	class Meta:
		verbose_name = "задание"
		verbose_name_plural = "задания"

class Slogan(models.Model):
	body = models.CharField('цитата', max_length=200)
	def __unicode__(self):
		return self.body

	class Meta:
		verbose_name = "цитата"
		verbose_name_plural = "цитаты"

class Mail(models.Model):
	name = models.CharField('имя отправителя',max_length=100)
	email = models.CharField(max_length=100)
	title = models.CharField('тема',max_length=100)
	body = models.CharField('сообщение',max_length=1000)
	date = models.DateTimeField('дата отправления', default=datetime.now)
	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name = "сообщение"
		verbose_name_plural = "сообщения"

class Order(models.Model):
	name = models.CharField('имя заказчика',max_length=100)
	telephone = models.CharField('номер телефона',max_length=100)
	category = models.ForeignKey(Category, verbose_name='категория')
	date_of_order = models.CharField('дата и время исполнения заказа',max_length=200, default="не указан")
	job_description = models.TextField('описание заказа', default="не указан")
	address = models.CharField('номер телефона',max_length=400, default="не указан")
	date_of_submition = models.DateTimeField('дата и время поступления заявки', default=datetime.now)
	def __unicode__(self):
		return self.name + " " + self.telephone

	class Meta:
		verbose_name = "заявка"
		verbose_name_plural = "заявки"
		

home/views.py
#python importings
from random import randint
#importings
from django.http import Http404
from django.core.paginator import Paginator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Information , SkillofUser , Skill , Category , Job, Slogan,Order
import requests


# Views
# @login_required(login_url=reverse('main:signin'))
def mainpage(request):
	#initialize variables
	args={}
	slogans = Slogan.objects.all()
	args.update(csrf(request))

	message = "JB:"
	#if user have complated registration

	if request.POST:
		name = request.POST.get('name', '')
		telephone = request.POST.get('telephone', '')
		category = request.POST.get('category', '')
		date_of_order = request.POST.get('date_order', '')
		job_description = request.POST.get('description', '')
		address = request.POST.get('address', '')

		category = get_object_or_404(Category, pk=category)
		new_order = Order.objects.create(name = name, job_description = job_description, telephone = telephone, category = category, date_of_order = date_of_order, address=address)
		new_order.save()
		# dealing with sms
		args["success_message"] = "ваша заявка принята , наши операторы свяжутся с вами в течении 5 минут"
		message += '\nname:' + str(name.encode('utf-8')) + '\n telephone:' + str(telephone.encode('utf-8')) + '\n date:' + str(date_of_order.encode('utf-8'))
		sms_url = 'http://smsc.ru/sys/send.php?login=traktorist221&psw=smsc120701&phones=996556606737&mes='
		sms_url += message
		r = requests.get(sms_url)
		

	# the method is get
	user = request.user
	args['user'] = user
	args['categories'] = Category.objects.all()
	args['slogan'] = slogans[0]
	return render_to_response('home/main.html',args)

def add_task(request):
	#initialize variables
	args={}
	slogans = Slogan.objects.all()
	args.update(csrf(request))

	args['categories'] = Category.objects.all()
	args['slogan'] = slogans[0]
	user = request.user
	args['user'] = user

	return render_to_response('home/add_job.html',args)
	
	

@login_required(login_url=reverse('main:signin'))
def profile(request):
	#init variables
	args={}
	slogans = Slogan.objects.all()
	#if user have complated registration
	if hasattr(request.user, 'information'):
		args['user'] = request.user
		args['slogan'] = slogans[randint(0,slogans.count()-1)]
		return render_to_response('home/profile.html',args)
	else:
		return redirect(reverse('home:create_info'))

@login_required(login_url=reverse('main:signin'))
def create_info(request):
	#initialize variables
	args={}
	slogans = Slogan.objects.all()
	args.update(csrf(request))
	user = request.user
	args['user'] = user
	#if user have complated registration
	if request.POST:
		user = request.user
		image = request.POST.get('image','')
		gender = request.POST.get('gender','')
		born_date = request.POST.get('born','')
		phone_number = request.POST.get('number','')
		category_id = request.POST.get('category','')
		category = Category.objects.get(pk=category_id)
		note = request.POST.get('description','')
		note_of_prices = request.POST.get('description_job_price','')
		information = Information.objects.create(user = user,image = image, gender = gender, category = category, born_date = born_date, phone_number = phone_number, note=note, note_of_prices=note_of_prices)
		information.save()
		return redirect(reverse('home:mainpage'))
	else:
		categories = Category.objects.all()
		args['categories'] = categories
		args['user'] = request.user
		args['slogan'] = slogans[randint(0,slogans.count()-1)]


		return render_to_response('home/create_info.html',args)

"""
@login_required(login_url=reverse('main:signin'))
def modify_info(request):
	#initialize variables
	args={}
	slogans = Slogan.objects.all()
	args.update(csrf(request))

	if request.POST:
		user = request.user
		first_name = request.POST.get('firstname','')
		last_name = request.POST.get('lastname','')
		email = request.POST.get('email','')
		image = request.POST.get('image','')
		gender = request.POST.get('gender','')
		born_date = request.POST.get('born','')
		phone_number = request.POST.get('number','')
		address = request.POST.get('address','')
		note = request.POST.get('note','')

		if first_name:
			user.first_name = first_name
		if last_name:
			user.last_name = last_name
		if email:
			user.email = email
		if image:
			user.information.image = image
		if gender:
			user.information.gender = gender
		if born_date:
			user.information.born_date = born_date
		if phone_number:
			user.information.phone_number = phone_number
		if address:
			user.information.address = address
		if note:
			user.information.note = note
		user.information.save()
		user.save()
		args['user'] = request.user
		args['slogan'] = slogans[randint(0,slogans.count()-1)]
		args['success_message'] = 'Профиль успешно отредактирован'
		return render_to_response('home/profile.html',args)
	else:
		#if user have complated registration
		if hasattr(request.user, 'information'):
			args["user"] = request.user
			args['slogan'] = slogans[randint(0,slogans.count()-1)]
			return render_to_response('home/modify_info.html',args)
		else:
			return redirect(reverse('home:create_info'))

@login_required(login_url=reverse('main:signin'))
def change_password(request):
	#init variables
	args = {}
	args.update(csrf(request))
	slogans = Slogan.objects.all()
	user = request.user
	args['user'] = user
	args['slogan'] = slogans[randint(0,slogans.count()-1)]

	if request.POST:
		password1 = request.POST.get('password1','')
		password2 = request.POST.get('password2','')

		if len(password1) < 6 or len(password2) < 6:
			args['password_error'] = 'Пароль должен состоять хотя бы из 6 символов'
			return render_to_response('home/change_password.html',args)
		if password1 == password2:
			user.set_password(password1)
			user.save()
			args['success_message'] = 'Ваш пароль успешно изменен'
		else:
			args['password_error'] = 'Пароли не совпадают'
		return render_to_response('home/change_password.html',args)
	else:
		return render_to_response('home/change_password.html',args)


@login_required(login_url=reverse('main:signin'))
def modify_skills(request):
	#init variables
	args = {}
	slogans = Slogan.objects.all()
	args.update(csrf(request))
	owned_skills = request.user.information.skillofuser_set.all().order_by('-experience')
	categories = Category.objects.all().order_by('title')
	all_skills = Skill.objects.all()
	owned_skills_skills = []
	for ownskill in owned_skills:
		owned_skills_skills.append(ownskill.skill)
	args['user'] = request.user
	args['owned_skills_list'] = owned_skills
	args['owned_skills'] = owned_skills_skills
	args['categories'] = categories
	args['all_skills'] = all_skills
	args['slogan'] = slogans[randint(0,slogans.count()-1)]
	
	if request.POST:
		action = request.POST.get('action','')
		if action == 'add':
			experience = request.POST.get('experience','')
			level = request.POST.get('level','')
			skill_id = request.POST.get('skill','')
			new_skill = request.user.information.skillofuser_set.create(experience=experience,skill=Skill.objects.get(pk=skill_id),level= level,user = request.user)
		if action == 'modify':
			experience = request.POST.get('experience','')
			level = request.POST.get('level','')
			skill_id = request.POST.get('skill','')
			skill = get_object_or_404(SkillofUser,pk=skill_id)
			skill.experience = experience
			skill.level = level
			skill.save()

		return redirect(reverse('home:modify_skills'))
	#if user have complated registration 
	if hasattr(request.user, 'information'):
		return render_to_response('home/modify_skills.html',args)
	#if user have not complated registration yet	
	return redirect(reverse('home:create_info'))

@login_required(login_url=reverse('main:signin'))
def delete_skill(request, skill_id):
	#init variables
	args = {}
	user = request.user
	skill = get_object_or_404(SkillofUser,pk=skill_id)
	if skill.user.user == user:
		skill.delete()

	return redirect(reverse('home:modify_skills'))


@login_required(login_url=reverse('main:signin'))
def list_jobs(request, category_id=-1):
	#init variables
	args = {}
	page_ranges = []
	slogans = Slogan.objects.all()
	if hasattr(request.user, 'information'):
		if int(category_id) > 0:
			this_category = get_object_or_404(Category, pk=category_id)
			args['this_category'] = this_category
			jobs = this_category.job_set.all().order_by('-date')
			categories = Category.objects.all().exclude(pk=category_id).order_by('title')
		
		#if category is not choosed
		else:
			jobs = Job.objects.all().order_by('-date')
			categories = Category.objects.all().order_by('title')

		paginator = Paginator(jobs, 10)

		if jobs.count() % 10 == 0:
			page_range = jobs.count()//10;
		else:
			page_range = jobs.count()//10 + 1;

		for i in range(1,page_range+1):
			page_ranges.append(i)
		page = request.GET.get('page')
		try:
			jobs_partial = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			jobs_partial = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			jobs_partial = paginator.page(paginator.num_pages)

		args['categories'] = categories
		args['page_ranges'] = page_ranges
		args['jobs_partial'] = jobs_partial
		args['slogan'] = slogans[randint(0,slogans.count()-1)]
		args['user'] = request.user
		return render_to_response('home/list_jobs.html',args)
	else:
		return redirect(reverse('home:create_info'))
	# if category is choosed
	


def job_info(request,job_id):
	#init variables
	args = {}
	slogans = Slogan.objects.all()
	
	job = get_object_or_404(Job, pk=job_id)

home/templates/home/not needed for now/job_info.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>JumuwBar.kg</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:mainpage' %}">JumuwBar.kg</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                     <li>
                        <a href="{% url 'home:list_workers'%}">исполнители</a>
                    </li>
                    <li class="active">
                        <a href="{%url 'home:list_jobs'%}">все задания</a>
                    </li>
                    <li>
                        <a href="{% url 'home:profile'%}">{{user.username}}</a>
                    </li>
                    <li>
                        <a><span data-toggle="modal" data-target="#signout"><span style="cursor:pointer">выйти</span></span></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url( {% static 'images/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{user.first_name}}</h1>
                        <hr class="small">
                        <span class="subheading">{{slogan}}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

   
    <hr>


    <div class="container">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
            <br>
            <hr>
                <h2 class="text-center">
                    {{job.title}}
                </h2>
                <br><br>
                <h4 class="text-center">
                    {{job.description|linebreaks}}
                </h4>
                <br>
                <h4>Цена : {{job.price}} (сом)</h4>

                <h4>Адрес : 
                {% if job.address%}
                    {{job.address}}
                {% else %}
                    не указан
                {% endif %}
                </h4>

                <br><hr>
                <h5 style="color:gray">задание было добавлено  : {{job.date}} пользователем : <a href="{%url 'home:look_profile' '1' job.user.pk %}">{{job.user}}</a> </h5>
                <h4 class="text-center"> Контактные данные пользователья: </h4>
                <h5 class="text-center"> Телефон : {{job.user.information.phone_number}}
                Email : {{job.user.email}}</h5>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

    <!-- Exit  model page -->
    <div class="modal fade" id="signout" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{user.first_name}} {{user.last_name}}</h4>
            </div>
            <div class="modal-body">
                <h4>вы уверены что хотите выйти?</h4>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <a href="{% url 'main:signout'%}"><button type="button" class="btn btn-primary">Выйти</button></a>
                </div>
            </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <h4 class="text-center"> поделиться </h4>
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 text-center">
                    <div class="share42init" data-title="Заголовок страницы"></div>
                    <script src="{% static 'js/share42.js' %}"></script>
                    <p class="copyright text-muted">Copyright &copy; JumuwBar.kg 2015. Ariet Nyshanbaev</p>
                </div>
            </div>


        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>